### ISSUE TITLE
cannot install due to error

### ISSUE THREAD

**Issue by r-mohammadi1** [rpatterson/github-apt-repos#1]
I am on debian 11, all packages up to date, here's what happens when i add -v to the install command:

Using pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9)
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-m9rq1izr
Created temporary directory: /tmp/pip-req-tracker-lgh6r1b_
Initialized build tracking at /tmp/pip-req-tracker-lgh6r1b_
Created build tracker: /tmp/pip-req-tracker-lgh6r1b_
Entered build tracker: /tmp/pip-req-tracker-lgh6r1b_
Created temporary directory: /tmp/pip-install-mfi1niuh
Collecting https://github.com/rpatterson/github-apt-repos.git
Created temporary directory: /tmp/pip-req-build-84t9vx4o
Created temporary directory: /tmp/pip-unpack-f_v38r8x
Getting credentials from keyring for github.com
Loading Gnome
Loading Google
Loading Windows (alt)
Loading file
Loading keyczar
Loading multi
Loading pyfs
Loading KWallet
Loading SecretService
Loading Windows
Loading chainer
Loading macOS
Looking up "https://github.com/rpatterson/github-apt-repos.git" in the cache
Returning cached "301 Moved Permanently" response (ignoring date and etag information)
Looking up "https://github.com/rpatterson/github-apt-repos" in the cache
Current age based on date: 155
Freshness lifetime from max-age: 0
Starting new HTTPS connection (1): github.com:443
https://github.com:443 "GET /rpatterson/github-apt-repos HTTP/1.1" 200 None
Downloading https://github.com/rpatterson/github-apt-repos.git
| 199 kB 151 kB/s  Updating cache with response from "https://github.com/rpatterson/github-apt-repos"
Caching due to etag

ERROR: Cannot unpack file /tmp/pip-unpack-f_v38r8x/github-apt-repos.git (downloaded from /tmp/pip-req-build-84t9vx4o, content-type: text/html; charset=utf-8); cannot detect archive format                                                               
ERROR: Cannot determine archive format of /tmp/pip-req-build-84t9vx4o
Exception information:
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 223,in _main
status = self.run(options, args)
File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
return func(self, options, args)
File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 346,in run
requirement_set = resolver.resolve(
File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 101, in resolve
r = self.factory.make_requirement_from_install_req(
File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 306, in make_requirement_from_install_req
cand = self._make_candidate_from_link(
File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 167, in _make_candidate_from_link
self._link_candidate_cache[link] = LinkCandidate(
File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 296, in __init__
super(LinkCandidate, self).__init__(
File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 144, in __init__
self.dist = self._prepare()
File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 222, in _prepare
dist = self._prepare_distribution()
File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 307, in _prepare_distribution
return self._factory.preparer.prepare_linked_requirement(
File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 480, in prepare_linked_requirement
return self._prepare_linked_requirement(req, parallel_builds)
File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 503, in _prepare_linked_requirement
local_file = unpack_url(
File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 263, in unpack_url
unpack_file(file.path, location, file.content_type)
File "/usr/lib/python3/dist-packages/pip/_internal/utils/unpacking.py", line 279, in unpack_file
raise InstallationError(
pip._internal.exceptions.InstallationError: Cannot determine archive format of /tmp/pip-req-build-84t9vx4o
Removed build tracker: '/tmp/pip-req-tracker-lgh6r1b_'

**Comment by hoffie** [comment]
Same issue here, but the following still works:
`pip install https://github.com/rpatterson/github-apt-repos/archive/refs/heads/master.tar.gz`

**Comment by dhurley94** [comment]
You use the tarball or tell pip to use git to install a package by prepending `git+` to the http/ssh url.

`pip install git+https://github.com/rpatterson/github-apt-repos.git`

**Comment by ronny-rentner** [comment]
I've had the same problem because the readme is wrong:
![image](https://user-images.githubusercontent.com/4419051/203705457-a9367792-b143-41a9-8f57-c3e0910f7214.png)

But @dhurley94's hint works!
